# System of Equations

## LU Factorization

Python implementation of LU Factorization

In [1]:
import numpy as np
from scipy.linalg import norm

eps = np.finfo(float).eps

# Find LU Factorization of a matrix
def LUfact(ax):
    matrix = ax.copy()
    n = len(matrix)
    lower = np.identity(n)

    for j in range(0, n-1):
        if abs(lower[j, j]) < eps:
            print ("Error")
            quit()
        else:
            for i in range(j+1, n):
                multiplication = matrix[i, j] / matrix[j, j]
                lower[i, j] = multiplication
                for k in range(j, n):
                    matrix[i, k] = matrix[i, k] - multiplication * matrix[j, k]

    return lower, matrix

# Use the LU factorization to solve system of linear equations
def solveLU(lower, upper, ans):
    copylower = lower.copy()
    copyupper = upper.copy()
    copyans = ans.copy()
    n = len(lower)
    x = np.zeros((n, 1))
    y = np.zeros((n, 1))

    for i in range(0, n):
        for j in range(n-1, -1, -1):
            copyans[i] = copyans[i] - copylower[i, j] * y[j]
        y[i] = copyans[i] / copylower[i, i]

    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            y[i] = y[i] - copyupper[i, j] * x[j]
        x[i] = y[i] / copyupper[i, i]

    return x

Find the LU factorization of the given matrices. Check by matrix multiplication  

a) $\begin{bmatrix} 3 & 1 & 2 \\ 6 & 3 & 4 \\ 3 & 1 & 5 \end{bmatrix}$

In [2]:
A = np.array([[3.0, 1.0, 2.0], [6.0, 3.0, 4.0], [3.0, 1.0, 5.0]])
lowerA, upperA = LUfact(A)
print("L:")
print(lowerA)
print("U:")
print(upperA)
print("Check the correction by matrix multiplication:")
print(np.matmul(lowerA, upperA))

L:
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]
U:
[[3. 1. 2.]
 [0. 1. 0.]
 [0. 0. 3.]]
Check the correction by matrix multiplication:
[[3. 1. 2.]
 [6. 3. 4.]
 [3. 1. 5.]]


b) $\begin{bmatrix} 4 & 2 & 0 \\ 4 & 4 & 2 \\ 2 & 2 & 3 \end{bmatrix}$

In [3]:
B = np.array([[4.0, 2.0, 0.0], [4.0, 4.0, 2.0], [2, 2, 3]])
lowerB, upperB = LUfact(B)
print("L:")
print(lowerB)
print("U:")
print(upperB)
print("Check the correction by matrix multiplication:")
print(np.matmul(lowerB, upperB))

L:
[[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.5 1. ]]
U:
[[4. 2. 0.]
 [0. 2. 2.]
 [0. 0. 2.]]
Check the correction by matrix multiplication:
[[4. 2. 0.]
 [4. 4. 2.]
 [2. 2. 3.]]


c) $\begin{bmatrix} 1 & -1 & 1 & 2 \\ 0 & 2 & 1 & 0 \\ 1 & 3 & 4 & 4 \\ 0 & 2 & 1 & -1 \end{bmatrix}$

In [4]:
C = np.array([[1.0, -1.0, 1.0, 2.0], [0.0, 2.0, 1.0, 0.0], [1.0, 3.0, 4.0, 4.0], [0.0, 2.0, 1.0, -1.0]])
lowerC, upperC = LUfact(C)
print("L:")
print(lowerC)
print("U:")
print(upperC)
print("Check the correction by matrix multiplication:")
print(np.matmul(lowerC, upperC))

L:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 2. 1. 0.]
 [0. 1. 0. 1.]]
U:
[[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0. -1.]]
Check the correction by matrix multiplication:
[[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 1.  3.  4.  4.]
 [ 0.  2.  1. -1.]]


Use the previous LU factorization to solve the system of linear equations

$\begin{bmatrix} 0 \\ 1 \\ 3 \end{bmatrix}$

In [5]:
ansA = np.array([0.0, 1.0, 3.0])
print(solveLU(lowerA, upperA, ansA))

[[-1.]
 [ 1.]
 [ 1.]]


# Naive Gaussian

Let $A$ be the $n x n$ matrix with entries $A_{i,j} = |i-j|+1$. Define $x = [1,...,1]^T$ and $b = Ax$. For $n=100,200,300,400,$ and $500$, use Naive Gaussian Elimination to compute $x_c$, the double precision computed solution. Calculate the infinity norm of the forward error for each solution. Find the five error magnification factors of the problems $Ax = b$, and compare with the corresponding condition numbers.

In [6]:
# Naive Gaussian Elimination implementation in Python
def naiveGaussian(ax, ans):
    n = len(ax)
    x = np.zeros((n, 1))
    matrixCopy = ax.copy()
    ansCopy = ans.copy()

    for j in range(0, n-1):
        if abs(matrixCopy[j, j]) < eps:
            print ("Error")
            quit()
        else:
            for i in range(j+1, n):
                mult = matrixCopy[i, j] / matrixCopy[j, j]
                for k in range(j + 1, n):
                    matrixCopy[i, k] = matrixCopy[i, k] - mult * matrixCopy[j, k]
                ansCopy[i] = ansCopy[i] - mult * ansCopy[j]

    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            ansCopy[i] = ansCopy[i] - matrixCopy[i, j] * x[j]
        x[i] = ansCopy[i] / matrixCopy[i, i]

    return x

# Auxuliary function to fill a square matrix of size n
def matrixFill(n):
    empmat = np.empty((n, n))
    for i in range(n):
        for j in range(n):
            empmat[i, j] = abs(i - j) + 1

    matone = np.ones(n)

    return empmat, matone

# Auxuliary functions to calculate backward error, forward error, relative errors
def backwardError(b, ax, guessVec):
    axa = ax.dot(guessVec)
    tonorm = b - axa
    abstonorm = np.absolute(tonorm)
    backwardErr = abstonorm.max()
    return backwardErr

def forwardError(x, guess):
    b = np.subtract(x, guess)
    absb = np.absolute(b)
    forErr = absb.max()
    return forErr


def relativeBack(r, b):
    normr = np.absolute(r).max()
    normb = np.absolute(b).max()
    relativeback = normr / normb
    return relativeback


def relativeFor(x, xa):
    b = np.subtract(x, xa)
    absb = np.absolute(b)
    absx = np.absolute(x)
    relativeforr = absb.max() / absx.max()
    return relativeforr

1) N = 100

In [7]:
# Create a matrix A and the [1, 1, ..., 1]^T matrix
matrix100, OneVector100 = matrixFill(100)
# Get the dot product of both matrix above and reshape it to one column
b100 = np.dot(matrix100, OneVector100).reshape((100, 1))
# Use naiveGaussian to solve for the Ax = b.
guess100 = naiveGaussian(matrix100, b100)
# Calculate the residual of matrix.
residual100 = b100 - (matrix100.dot(guess100).reshape(100, 1))
# Calculate infinite norm of the matrix A
mag100 = norm(matrix100, np.inf)
# Get the inverse of matrix A and calculate its infinite norm
inverse100 = np.linalg.inv(matrix100)
maginverse100 = norm(inverse100, np.inf)
# Calculate the condition number of 100 x 100 matrix.
condition100 = mag100 * maginverse100

print("Forward Error", forwardError(OneVector100, guess100))
print("Backward Error", backwardError(b100, matrix100, guess100))
print("Relative Forward", relativeFor(OneVector100, guess100))
print("Relative Backward", relativeBack(residual100, b100))
print("Error Magnification Factor", relativeFor(OneVector100, guess100) / relativeBack(residual100, b100))
print("Condition number", condition100)

Forward Error 5.2911230952190635e-11
Backward Error 2.1373125491663814e-10
Relative Forward 5.2911230952190635e-11
Relative Backward 4.232302077557191e-14
Error Magnification Factor 1250.176144863697
Condition number 10100.000000007769


2) N = 200

In [8]:
# Create a matrix A and the [1, 1, ..., 1]^T matrix
matrix200, OneVector200 = matrixFill(200)
# Get the dot product of both matrix above and reshape it to one column
b200 = np.dot(matrix200, OneVector200).reshape((200, 1))
# Use naiveGaussian to solve for the Ax = b.
guess200 = naiveGaussian(matrix200, b200)
# Calculate the residual of matrix.
residual200 = b200 - (matrix200.dot(guess200).reshape(200, 1))
# Calculate infinite norm of the matrix A
mag200 = norm(matrix200, np.inf)
# Get the inverse of matrix A and calculate its infinite norm
inverse200 = np.linalg.inv(matrix200)
maginverse200 = norm(inverse200, np.inf)
# Calculate the condition number of 200 x 200 matrix.
condition200 = mag200 * maginverse200

print("Forward Error", forwardError(OneVector200, guess200))
print("Backward Error", backwardError(b200, matrix200, guess200))
print("Relative Forward", relativeFor(OneVector200, guess200))
print("Relative Backward", relativeBack(residual200, b200))
print("Error Magnification Factor", relativeFor(OneVector200, guess200) / relativeBack(residual200, b200))
print("Condition number", condition200)

Forward Error 5.781792822290299e-10
Backward Error 1.8408172763884068e-09
Relative Forward 5.781792822290299e-10
Relative Backward 9.158294907405009e-14
Error Magnification Factor 6313.176066884881
Condition number 40200.000000148306


3) N = 300

In [9]:
# Create a matrix A and the [1, 1, ..., 1]^T matrix
matrix300, OneVector300 = matrixFill(300)
# Get the dot product of both matrix above and reshape it to one column
b300 = np.dot(matrix300, OneVector300).reshape((300, 1))
# Use naiveGaussian to solve for the Ax = b.
guess300 = naiveGaussian(matrix300, b300)
# Calculate the residual of matrix.
residual300 = b300 - (matrix300.dot(guess300).reshape(300, 1))
# Calculate infinite norm of the matrix A
mag300 = norm(matrix300, np.inf)
# Get the inverse of matrix A and calculate its infinite norm
inverse300 = np.linalg.inv(matrix300)
maginverse300 = norm(inverse300, np.inf)
# Calculate the condition number of 200 x 200 matrix.
condition300 = mag300 * maginverse300

print("Forward Error", forwardError(OneVector300, guess300))
print("Backward Error", backwardError(b300, matrix300, guess300))
print("Relative Forward", relativeFor(OneVector300, guess300))
print("Relative Backward", relativeBack(residual300, b300))
print("Error Magnification Factor", relativeFor(OneVector300, guess300) / relativeBack(residual300, b300))
print("Condition number", condition300)

Forward Error 3.030261375158716e-09
Backward Error 1.5767000149935484e-08
Relative Forward 3.030261375158716e-09
Relative Backward 3.492137353252599e-13
Error Magnification Factor 8677.38312851959
Condition number 90300.00000073461


4) N=400

In [10]:
# Create a matrix A and the [1, 1, ..., 1]^T matrix
matrix400, OneVector400 = matrixFill(400)
# Get the dot product of both matrix above and reshape it to one column
b400 = np.dot(matrix400, OneVector400).reshape((400, 1))
# Use naiveGaussian to solve for the Ax = b.
guess400 = naiveGaussian(matrix400, b400)
# Calculate the residual of matrix.
residual400 = b400 - (matrix400.dot(guess400).reshape(400, 1))
# Calculate infinite norm of the matrix A
mag400 = norm(matrix400, np.inf)
# Get the inverse of matrix A and calculate its infinite norm
inverse400 = np.linalg.inv(matrix400)
maginverse400 = norm(inverse400, np.inf)
# Calculate the condition number of 200 x 200 matrix.
condition400 = mag400 * maginverse400

print("Forward Error", forwardError(OneVector400, guess400))
print("Backward Error", backwardError(b400, matrix400, guess400))
print("Relative Forward", relativeFor(OneVector400, guess400))
print("Relative Backward", relativeBack(residual400, b400))
print("Error Magnification Factor", relativeFor(OneVector400, guess400) / relativeBack(residual400, b400))
print("Condition number", condition400)

Forward Error 4.480377846505235e-09
Backward Error 5.1280949264764786e-08
Relative Forward 4.480377846505235e-09
Relative Backward 6.394133324783639e-13
Error Magnification Factor 7007.013490224399
Condition number 160400.00000270313


5) N = 500

In [11]:
# Create a matrix A and the [1, 1, ..., 1]^T matrix
matrix500, OneVector500 = matrixFill(500)
# Get the dot product of both matrix above and reshape it to one column
b500 = np.dot(matrix500, OneVector500).reshape((500, 1))
# Use naiveGaussian to solve for the Ax = b.
guess500 = naiveGaussian(matrix500, b500)
# Calculate the residual of matrix.
residual500 = b500 - (matrix500.dot(guess500).reshape(500, 1))
# Calculate infinite norm of the matrix A
mag500 = norm(matrix500, np.inf)
# Get the inverse of matrix A and calculate its infinite norm
inverse500 = np.linalg.inv(matrix500)
maginverse500 = norm(inverse500, np.inf)
# Calculate the condition number of 200 x 200 matrix.
condition500 = mag500 * maginverse500

print("Forward Error", forwardError(OneVector500, guess500))
print("Backward Error", backwardError(b500, matrix500, guess500))
print("Relative Forward", relativeFor(OneVector500, guess500))
print("Relative Backward", relativeBack(residual500, b500))
print("Error Magnification Factor", relativeFor(OneVector500, guess500) / relativeBack(residual500, b500))
print("Condition number", condition500)

Forward Error 9.632996178510211e-09
Backward Error 2.5116605684161186e-08
Relative Forward 9.632996178510211e-09
Relative Backward 2.0053178190947055e-13
Error Magnification Factor 48037.25417878647
Condition number 250500.00000672974
